name: Deploy Static Site to S3
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Debug directory structure
        run: |
          echo "Current path: $(pwd)"
          ls -la
          echo "Contents:"
          ls -la Project-Cloud-computing/
          ls -la Project-Cloud-computing/js/

      - name: Sync files
        run: |
          cd Project-Cloud-computing || exit 1
          echo "Current path after cd: $(pwd)"
          
          # Sync HTML files from js folder to root
          aws s3 sync ./js s3://${{ secrets.AWS_S3_BUCKET }} \
            --exclude "*" \
            --include "*.html" \
            --content-type "text/html" \
            --acl public-read

          # Sync CSS files
          aws s3 sync ./css s3://${{ secrets.AWS_S3_BUCKET }}/css \
            --content-type "text/css" \
            --acl public-read

          # Sync images
          aws s3 sync ./images s3://${{ secrets.AWS_S3_BUCKET }}/images \
            --acl public-read

          # Sync root files
          if [ -f "./README.md" ]; then
            aws s3 cp ./README.md s3://${{ secrets.AWS_S3_BUCKET }}/README.md \
              --acl public-read
          fi

      - name: Verify upload
        run: |
          aws s3 ls s3://${{ secrets.AWS_S3_BUCKET }} --recursive