name: Deploy Static Site to S3 and EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Verify directory structure
        run: |
          ls -la
          echo "Current path: $(pwd)"

      - name: Sync website content to S3
        run: |
          aws s3 sync . s3://${{ secrets.AWS_S3_BUCKET }} \
            --delete \
            --acl public-read \
            --exclude ".git/*" \
            --exclude ".terraform/*"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7

      - name: Terraform Init
        working-directory: terraform
        run: terraform init -input=false

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform Plan and Apply
        working-directory: terraform
        run: |
          terraform plan -var="s3_bucket_name=${{ secrets.AWS_S3_BUCKET }}"
          terraform apply -auto-approve -var="s3_bucket_name=${{ secrets.AWS_S3_BUCKET }}"

      - name: Verify deployment
        run: |
          aws s3 ls s3://${{ secrets.AWS_S3_BUCKET }} --recursive
          echo "Deployment completed successfully"