name: Deploy Static Site to S3

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Verify directory structure
        run: |
          ls -la
          echo "Current path: $(pwd)"

      - name: Sync all website content
        run: |
          aws s3 sync . s3://${{ secrets.AWS_S3_BUCKET }} --delete --acl public-read

      - name: Move index.html to root if needed
        run: |
          aws s3 cp index.html s3://${{ secrets.AWS_S3_BUCKET }}/index.html \
            --content-type "text/html" \
            --acl public-read

      - name: Verify S3 upload
        run: |
          aws s3 ls s3://${{ secrets.AWS_S3_BUCKET }} --recursive
      - name: Move index.html to root if needed
        run: |
          aws s3 cp app/index.html s3://${{ secrets.AWS_S3_BUCKET }}/index.html \
            --content-type "text/html" \
            --acl public-read